### ISSUE TITLE
NoNethodError form_with Rails 5.0.7.2

### ISSUE THREAD

**Issue by dgbtech** [code-and-effect/effective_bootstrap#11]
Iam trying to use effective_datatables, my problem is now with form_with in effective_bootstrap:

```
NoMethodError at /

undefined method `form_with' for #<#<Class:0x000000000453e338>:0x0000000004553260>
Did you mean?  form_tag

effective_bootstrap (0.6.10) app/helpers/effective_form_builder_helper.rb
50 form_with(**options.merge(builder: Effective::FormBuilder), &block)

```
Does this version support Rails 5.0.7.2?? TIA

**Comment by matt-riemer** [comment]
I think you need to use Rails 5.1 to use these gems!

The `form_with` only appeared in Rails 5.1, so I think you need to use Rails 5.1 or greater for effective_bootstrap!
