### ISSUE TITLE
max-length issue with datatable responsive 

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_bootstrap#14]
Hello,

I think this commit broke some style in effective datatable: 

https://github.com/code-and-effect/effective_bootstrap/commit/a692d5a9244870115a087b10f724b387a55f1b03#diff-3ade6f276945b98737066b20b07a639902f672bfa5dddfdfb5fd3914aca1144fR6

Specifically the `maxlength: 255`. That is causing the columns which are regular input field to take a lot of space.

This is current behaviour; notice the "Total" column is taking half the table.

<img width="1626" alt="Screenshot 2021-03-05 at 10 42 56" src="https://user-images.githubusercontent.com/259568/110097858-cd25a300-7d9f-11eb-8c8c-25027074072e.png">

And this is with master branch of effective_boostrap but with the `maxlength: 255` removed:

<img width="1622" alt="Screenshot 2021-03-05 at 10 43 53" src="https://user-images.githubusercontent.com/259568/110097867-cf87fd00-7d9f-11eb-871f-dc513a6368bb.png">

Notice the width of fields is evenly distributed.

**Comment by matt-riemer** [comment]
Heyo,

That's weird, I don't get the same effect on my browser haha :/

I've reverted the change in effective_bootstrap 0.9.16


The idea is that every text field should have maxlength 255 so a client can't submit a string more than 255 in length, which can straight up cause rails to throw a database exception

But, yea, it shouldn't be rendering so wiiide!

Try out 0.9.16

Thanks, sorry!

**Comment by Nerian** [comment]
Thanks! Working fine now.

It's strange you didn't get the same behaviour. I am using Chrome 88.0 in Mac OS.
