### ISSUE TITLE
Incorrect dropdown split 

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_bootstrap#5]
Hi,

```
= dropdown split: true, btn: 'btn-outline-dark'
    = dropdown_link_to t('general.show'), member_dashboard.root_path(resource.account)
```

When using `split: true` and custom `btn` the dropdown button is correct styled, but the split button is not.

In order to get it right it needs to be changed to:

```
= dropdown split: true, btn: 'btn-outline-dark'
    = dropdown_link_to t('general.show'), member_dashboard.root_path(resource.account), class: 'btn btn-outline-dark'
```

It would be nice if dropdown's `btn` was added to  the class of `dropdown_link_to` automatically.

**Comment by matt-riemer** [comment]
Pretty sure this got fixed finally lol!
