### ISSUE TITLE
Modularity

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_bootstrap#8]
Hi,

I was wondering if we could make including this bit configurable?

https://github.com/code-and-effect/effective_bootstrap/blob/e38ff0726638dc212586c5ce4dae55ffecd5be2c/app/assets/javascripts/effective_bootstrap/base.js.coffee#L23-L41

That bit changes all `data-confirms` in the whole site. I don't really use EffectiveBootstrap forms because I use SimpleForm, but since it is a dependency of EffectiveDatatable I have to include it. I don't use EffectiveBootstrap's data-confirm because it doesn't fit my design. It also breaks when using Dropdowns. In this case I prefer the Rails' default.

What I do right now to handle this is manually including all the effective_bootstrap files and  overwriting effective_bootstrap/base with my own version, which has the relevant code commented out. It's kind of hacky :)

````
//= require effective_datatables

//------
//-- require effective_bootstrap
//-----

//= require ./effective_bootstrap/base
//= require effective_bootstrap/form

//= require effective_datetime/input
//= require effective_date/input
//= require effective_time/input
//= require effective_checks/input
//= require effective_editor/input
//= require effective_file/input
//= require effective_phone/input
//= require effective_price/input
//= require effective_radio/input
//= require effective_select/input
````

So I was wondering if can we make this optional? Maybe an option in `EffectiveBootstrap.setup` so I can opt-out. Or even an optional module/js file that is opt-in.

It is not a deal breaker, I can keep patching up to make it work. But I think it would be nice if we could make EffectiveBootstrap more modular.

What do you think?

**Comment by matt-riemer** [comment]
Yes! Great idea!  This has been implemented in effective_bootstrap 0.4.7

Add

`config.use_custom_data_confirm = false`

to your `config/initializers/effective_bootstrap.rb` file.

https://github.com/code-and-effect/effective_bootstrap/commit/3b32e2b20af9b9a1bdf05ba39f9f81475e097b4e
